services:
  postgres:
    image: postgres:16-alpine3.20
    container_name: postgres
    environment:
      - POSTGRES_DB=productDB
      - POSTGRES_USER=yuji
      - POSTGRES_PASSWORD=yuji
    volumes:
      - ./postgres16:/var/lib/postgresql/data
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=yuji@yopmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 80:80

  mongo:
    image: mongo:6.0.16-rc0-jammy
    ports:
      - 27017:27017

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - 'zookeeper'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      #      ALLOW_PLAINTEXT_LISTENER: yes
      #      KAFKA_ENABLE_KRAFT: no
      #      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      #      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      #      KAFKA_LISTENERS: PLAINTEXT://:9092
      #
      #      KAFKA_BROKER_ID: 1
      #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      #      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - '8082:8080'
    depends_on:
      - 'kafka'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      #      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: localhost:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  app-tier:
    driver: bridge
