spring:
  application.name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/productDB
    username: yuji
    password: yuji
  kafka:
    bootstrap-servers:
      - localhost:9091
      - localhost:9092
      - localhost:9093
    template:
      default-topic: user-service-event
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

springdoc:
  version: 1.0.0
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-doc

#logging:
#  level:
#    root: DEBUG
application-description: '@project.description@'
application-version: '@project.version@'
