server:
  port: 8081
spring:
  application.name: order-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order-service
  kafka:
    bootstrap-servers:
      - localhost:9091
      - localhost:9092
      - localhost:9093
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.LongDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer

springdoc:
  version: 1.0.0
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-doc

#logging:
#  level:
#    root: DEBUG
application-description: '@project.description@'
application-version: '@project.version@'
